replicaCount: 2

image:
  repository: 196750375574.dkr.ecr.us-east-2.amazonaws.com/cloudops-gitops-dev-demo-app
  tag: "0.1.0-staging"
  pullPolicy: IfNotPresent

environment:
  name: staging

failureMode:
  enabled: false

serviceMonitor:
  enabled: true
  labels:
    release: cloudops-observability

resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi
