apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloudops-observability-quota
  namespace: cloudops-observability
spec:
  hard:
    pods: "30"
    services: "20"
    configmaps: "60"
    secrets: "60"
    persistentvolumeclaims: "4"
