apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloudops-staging-quota
  namespace: cloudops-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "15"
    services: "5"
