replicaCount: 3

image:
  repository: 196750375574.dkr.ecr.us-east-2.amazonaws.com/cloudops-gitops-dev-demo-app
  tag: "0.1.0-prod"
  pullPolicy: IfNotPresent

environment:
  name: prod

failureMode:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
