apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-demo-prod
  namespace: argocd
  labels:
    cloudops.io/environment: prod
spec:
  project: cloudops-gitops-platform
  sources:
    - repoURL: REPO_URL_PLACEHOLDER
      targetRevision: HEAD
      path: charts/cloudops-demo-app
      helm:
        releaseName: cloudops-demo-prod
        valueFiles:
          - $values/VALUES_ROOT_PLACEHOLDER/prod/values.yaml
    - repoURL: REPO_URL_PLACEHOLDER
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
