replicaCount: 1

image:
  repository: cloudops-demo-app
  tag: "0.1.0-dev"
  pullPolicy: IfNotPresent

environment:
  name: dev

failureMode:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
